#ifndef TYPEFORGAME_HPP
#define TYPEFORGAME_HPP

enum typeAction {NOT_SET, PLACE, PLAY, WIN};
enum typePlayer {RED = 0, BLUE, MAGENTA, CYAN, NO_PLAYER};
enum typeSend {THE_MAP, CLICK_TO, UPDATE_MAP, UPDATE_IS_SELECTED, NEW_CASE, ERASE_CASE, UPDATE_IS_SELECTED_IS_HEAD, RECT_FOR_PLACE, ERASE_RECT, YOU_ARE, CHANGE_ACTION, I_BELIEVE_I_CAN_LEAVE, SET_MOVE_TOTAL, SET_MOVE_NUMBER, AUDIO_STREAM, END_OF_AUDIO_STREAM, TYPE_AUDIO};
enum typeSound {ALL = 0, END_TURN_ONLY, NEVER};

#endif
